amaru/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('login.urls')),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^administrador/', include('administrador.urls', namespace="administrador")),
    url(r'^usuario/', include('usuario.urls', namespace="usuario")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate/$', views.validate, name='validate'),
    url(r'^end_session/$', views.end_session, name='end_session'),
]

login/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect

# For user authentication using Django system
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def index(request):
    """
        Vista predeterminada para iniciar sesión en el servidor.
        Si no existen usuarios, se pide la creación de un administrador,
        caso contrario, se muestra un formulario de inicio de sesión.
        Este módulo utiliza el sistema de autenticación de Django
    :param request:
    :return:
    """

    user_id = verificar_admin(request)

    if user_id >= 1:
        request.session['tipo_usuario'] = 'Administrador'
        return redirect('administrador:menu_principal', permanent=True)
    elif user_id == -2:
        request.session['tipo_usuario'] = 'Profesor'
        return redirect('usuario:menu_principal', permanent=True)
    elif user_id == -3:
        request.session['tipo_usuario'] = 'Estudiante_Colegio'
        return redirect('usuario:menu_principal', permanent=True)
    elif user_id == -4:
        request.session['tipo_usuario'] = 'Estudiante_Universitario'
        return redirect('usuario:menu_principal', permanent=True)
    else:
        return render(request, 'login/login.html')


def validate(request):
    """
        En caso de existir usuarios registrados, se inicia el proceso de
        auntenticación y se mostrará la página correspondiente, para un
        usuario Normal o para un usuario Administrador.
    :param request:
    :return:
    """

    username = request.POST.get('username', "")
    password = request.POST.get('password', "")

    if 'login' in request.POST:
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                init_session(request, user)

    if 'registrarse' in request.POST:
        return redirect('administrador:seleccionar_cen_edu', permanent=True)

    return redirect('login:index')


def init_session(request, user):
    """
        Permite finalizar la sesión, eliminando del servidor
        todo rastro de la sesión
    :param request:
    :return:
    """

    login(request, user)
    request.session['user_id'] = user.id


def end_session(request):
    """
        Permite finalizar la sesión, eliminando del servidor
        todo rastro de la sesión
    :param request:
    :return:
    """

    logout(request)

    return redirect('login:index', permanent=True)


def verificar_admin(request):
    """
        Verifica si un usuario ha iniciado sesión y ha sido autenticado como administrador
    :param request:
    :return:
        -1 : El usuario no está autenticado.
        -2 : El usuario está autenticado, pero no es un administrador
    """

    try:
        user_id = request.session['user_id']  # request.user.is_authenticated()
        user = User.objects.get(pk=user_id)
    except KeyError:
        user_id = 0
        user = None

    if user is None:
        return -1
    elif user_id != 0 and user.is_active and user.is_staff and user.is_superuser:
        return user_id
    else:
        return -2

login/templates/login/login.html
{% extends "login_base.html" %}

{% block title %} Iniciar Sesión {% endblock %}

{% block content %}
    <h1 class="titulo">
        Iniciar Sesión
    </h1>
    <div class="login">
    <form name="loginUser" action="{% url 'login:validate' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                    <td class="etiqueta"><label for="username">Username:</label></td>
                    <td class="control"><input id="username" type="text" name="username" autofocus="1"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="password">Password:</label></td>
                    <td class="control"><input id="password" type="password" name="password" /></td>
                </tr>
                <tr class="botones">
                    <td colspan = "2">
                        <div class="botones">
                            <input class="boton" id="login" type="submit" name="login" value="LogIn" />
                            &nbsp;&nbsp;
                            <input class="boton" id="registrase" type="submit" name="registrarse" value="Registrarse" />
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}