administrador/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.menu_principal, name='menu_principal'),
    url(r'^menu_principal/$', views.menu_principal, name='menu_principal'),
    url(r'^crear_usuario/$', views.crear_usuario, name='crear_usuario'),
    url(r'^seleccionar_cen_edu/$', views.seleccionar_cen_edu, name='seleccionar_cen_edu'),
    url(r'^registrar_cen_edu/$', views.registrar_cen_edu, name='registrar_cen_edu'),
    url(r'^registrar_cen_edu/#(?P<anchor>[-_\w]+)$', views.registrar_cen_edu, name='registrar_cen_edu'),
    url(r'^departamentos/$', views.lista_departamentos),
    url(r'^departamentos/(?P<pk>[0-9]+)/$', views.detalle_departamento),
    url(r'^centro_educativo/(?P<departamento>[-_\w]+)/(?P<tipo>[-_\w]+)$', views.lista_cen_edu),
]

amaru/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', include('login.urls')),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^administrador/', include('administrador.urls', namespace="administrador")),
    url(r'^usuario/', include('usuario.urls', namespace="usuario")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate/$', views.validate, name='validate'),
    url(r'^end_session/$', views.end_session, name='end_session'),
]

administrador/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Usuario(models.Model):
    TIPO_CHOICES = (
        ('Estudiante_Colegio', 'Estudiante_Colegio'),
        ('Estudiante_Universitario', 'Estudiante_Universitario'),
        ('Profesor', 'Profesor'),
        ('Administrador', 'Administrador')
    )
    user = models.OneToOneField(User, primary_key='True')
    tipo = models.CharField(max_length=50, default='Estudiante_Colegio', choices=TIPO_CHOICES)
    direccion = models.CharField(max_length=100, blank='True', null='True')
    telefono = models.IntegerField(blank='True', null='True')
    habilitado = models.BooleanField(default='False')

    def __str__(self):              # __unicode__ on Python 2
        if self.user.last_name != "" and self.user.first_name != "":
            rn = self.user.last_name + ', ' + self.user.first_name
        else:
            rn = 'Usuario sin nombre'

        return rn

DEPARTAMENTO_CHOICES = (
    ('La Paz'.encode(encoding='utf-8'), 'La Paz'.encode(encoding='utf-8')),
    ('Oruro'.encode(encoding='utf-8'), 'Oruro'.encode(encoding='utf-8')),
    ('Potosi'.encode(encoding='utf-8'), 'Potosí'.encode(encoding='utf-8')),
    ('Cochabamba'.encode(encoding='utf-8'), 'Cochabamba'.encode(encoding='utf-8')),
    ('Chuquisaca'.encode(encoding='utf-8'), 'Chuquisaca'.encode(encoding='utf-8')),
    ('Tarija'.encode(encoding='utf-8'), 'Tarija'.encode(encoding='utf-8')),
    ('Pando'.encode(encoding='utf-8'), 'Pando'.encode(encoding='utf-8')),
    ('Beni'.encode(encoding='utf-8'), 'Beni'.encode(encoding='utf-8')),
    ('Santa Cruz'.encode(encoding='utf-8'), 'Santa Cruz'.encode(encoding='utf-8')),
)

TIPO_CHOICES = (
    ('Colegio', 'Colegio'),
    ('Universidad', 'Universidad'),
)


class Departamento(models.Model):
    departamento = models.CharField(max_length=30, unique='True', choices=DEPARTAMENTO_CHOICES)

    def primary_key(self):
        return str(self.pk)

    def __str__(self):              # __unicode__ on Python 2
        return self.departamento


class CentroEducativo(models.Model):
    centro_educativo = models.CharField(max_length=50, unique='True')
    tipo = models.CharField(max_length=50, default='Estudiante_Colegio', choices=TIPO_CHOICES)
    departamento = models.ForeignKey(Departamento)
    direccion = models.CharField(max_length=100, blank='True', null='True')
    telefono = models.IntegerField(blank='True', null='True')
    habilitado = models.BooleanField(default='False')

    def __str__(self):              # __unicode__ on Python 2
        return self.centro_educativo

administrador/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from .models import Departamento, CentroEducativo
from administrador.serializers import DepartamentoSerializer, CenEduSerializer

# Create your views here.


class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


@csrf_exempt
def lista_cen_edu(request, departamento, tipo):
    """
        Muestra una lista de todos los centros educativos de un determinado tipo en un departamento
    """
    try:
        cen_edu = CentroEducativo.objects.filter(departamento=departamento, tipo=tipo).order_by('pk')
    except CentroEducativo.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = CenEduSerializer(cen_edu, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = CenEduSerializer(cen_edu, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        cen_edu.delete()
        return HttpResponse(status=204)



@csrf_exempt
def lista_departamentos(request):
    """
        Muestra una lista de todos los departamentos, o permite crear uno nuevo
    """
    if request.method == 'GET':
        departamentos = Departamento.objects.order_by('pk')
        serializer = DepartamentoSerializer(departamentos, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = DepartamentoSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data, status=201)
        return JSONResponse(serializer.errors, status=400)


@csrf_exempt
def detalle_departamento(request, pk):
    """
        Obtener o modificar un registro
    """
    try:
        departamento = Departamento.objects.get(pk=pk)
    except Departamento.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = DepartamentoSerializer(departamento)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = DepartamentoSerializer(departamento, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        departamento.delete()
        return HttpResponse(status=204)


def menu_principal(request):
    """
        Muestra en pantalla el menú principal del usuario administrador
    :param request:
    :return:
    """

    tipo_usuario = request.session.get('tipo_usuario', "")

    if tipo_usuario == 'Administrador':
        context = {'debug_info': 'Administrador Menu Principal: Menu Principal Tipo_Usuario: ' + tipo_usuario}
        return render(request, 'administrador/menu_principal.html', context)
    else:
        return redirect('login:index')


def crear_usuario(request):
    """
        Permite crear un usuario nuevo en el sistema
    :param request:
    :return:
    """

    if 'cancel' in request.POST:
        return redirect("login:index")

    tipo_usuario = request.session.get('tipo_usuario', "")

    context = {'debug_info': 'Administrador Menu Principal: Crear Usuario',
               'tipo_usuario': tipo_usuario}

    return render(request, 'administrador/crear_usuario.html', context)


def registrar_cen_edu(request):
    """
        Permite registrar un colegio en el sistema
    :param request:
    :return:
    """

    if 'cancel' in request.POST:
        return redirect("login:index")

    tipo_usuario = request.session.get('tipo_usuario', "")

    if tipo_usuario != 'Administrador' and \
                    tipo_usuario != 'Profesor' and \
                    tipo_usuario != 'Estudiante_Colegio' and \
                    tipo_usuario != 'Estudiante_Universitario':
        tipo_usuario = 'Nuevo_Usuario'

    context = {'debug_info': 'Administrador Menu Principal: Registrar Colegio Tipo_Usuario: ' + tipo_usuario,
               'tipo_usuario': tipo_usuario}

    return render(request, 'administrador/registrar_cen_edu.html', context)


def seleccionar_cen_edu(request):
    """

    :param request:
    :return:
    """
    if 'cancel' in request.POST:
        return redirect("login:index")

    context = {'debug_info': 'Administrador Menu Principal: Crear Usuario',
               'tipo_usuario': 'NUEVO USUARIO'}
    return render(request, 'administrador/seleccionar_cen_edu.html', context)

administrador/templates/administrador/consultar_colegios.html
{% extends "administrador_base.html" %}
{% load staticfiles %}

{% block title %} Consultar Colegios {% endblock %}

{% block content %}

    <script src="{% static "administrador/verificar_colegio.js" %}"></script>

    <h1 class="titulo">
        ADMINISTRADOR <BR />
        Consultar Colegios
    </h1>

    <div class="tabla">
    <form name="registrar_colegio" action="{% url 'administrador:registrar_colegio' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                    <td class="etiqueta"><label for="colegio">Colegio:</label></td>
                    <td class="control"><input id="colegio" type="text" name="colegio" maxlength="100" autofocus="1" value="{{ colegio }}"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="departamento">Departamento:</label></td>
                    <td class="control">
                        <select id="departamento" name="departamento" />
                        {% for d in departamentos %}
                            <option value="{{ d.pk }}" {% if d.primary_key == id_departamento %}selected{% endif %}>
                                {{ d.departamento }}
                            </option>
                        {% endfor %}
                        </select>
                    </td>
                </tr>

                <tr class="botones">
                    <td colspan = "2">
                        <input id="origen" type="hidden" name="origen" value="Registrar_Colegio">
                        <input class="boton" id="create" name="create" type="submit" value="Crear" onclick="return validateForm()"/>
                        <input class="boton" id="cancel" name="cancel" type="submit" value="Cancelar" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}

administrador/templates/administrador/crear_usuario.html
{% extends "administrador_base.html" %}

{% block title %} Crear Usuario {% endblock %}

{% block content %}
    <h1 class="titulo">
        {% if tipo_usuario == "Administrador" %}
            {{ tipo_usuario }} <BR />
        {% endif %}
        Crear un nuevo usuario
    </h1>

    <div class="tabla">
    <form name="crear_usuario" action="{% url 'administrador:crear_usuario' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                    <td class="etiqueta"><label for="nombre">Nombre:</label></td>
                    <td class="control"><input id="nombre" type="text" name="nombre" maxlength="100" autofocus="1"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="apellido">Apellido:</label></td>
                    <td class="control"><input id="apellido" type="text" name="apellido" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="email">E-Mail:</label></td>
                    <td class="control"><input id="email" type="text" name="email" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="radio" colspan = "2">
                    {% if tipo_usuario == "Administrador" %}
                        <label for="admin">Administrador</label>
                        <input id=admin" type="radio" name="tipo_usuario" value="admin">
                        &nbsp;&nbsp;
                    {% endif %}
                        <label for="profesor">Profesor</label>
                        <input id="profesor" type="radio" name="tipo_usuario" value="profesor">                         </td>
                </tr>
                <tr>
                    <td class="radio" colspan = "2">
                        <label for="estudiante_colegio">Estudiante Colegio</label>
                        <input id="estudiante_colegio" type="radio" name="tipo_usuario" value="estudiante_colegio" checked>                        &nbsp;&nbsp;
                        &nbsp;&nbsp;
                        <label for="estudiante_universitario">Estudiante Universitario</label>
                        <input id="estudiante_universitario" type="radio" name="tipo_usuario" value="estudiante_universitario">
                    </td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="username">Username:</label></td>
                    <td class="control"><input id="username" type="text" name="username" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="password">Password:</label></td>
                    <td class="control"><input id="password" type="password" name="password" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="direccion">Dirección:</label></td>
                    <td class="control"><input id="direccion" type="text" name="direccion" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="telefono">Teléfono:</label></td>
                    <td class="control"><input id="telefono" type="text" name="telefono" maxlength="100"/></td>
                </tr>
                {% if tipo_usuario == "Administrador" %}
                <tr>
                    <td class='checkbox' colspan = "2">
                        <label for="habilitado">Habilitado</label>
                        <input type="checkbox" name="habilitado" value="habilitado">
                    </td>
                </tr>
                {% endif %}
                <tr class="botones">
                    <td colspan = "2">
                        <input id="origen" type="hidden" name="origen" value="Crear_Usuario">
                        <input class="boton" id="create" name="create" type="submit" value="Crear" />
                        <input class="boton" id="cancel" name="cancel" type="submit" value="Cancelar" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}

administrador/templates/administrador/menu_principal.html
{% extends "administrador_base.html" %}

{% block title %} ADMINISTRADOR - MENU PRINCIPAL {% endblock %}

{% block content %}
    <h1 class="titulo">
        Administrador <BR />
        Menu Principal
    </h1>

    <div class="tabla">
        <table class="formulario">
            <tbody>
                <tr>
                    <td><a class="enlace" href="{%  url 'administrador:crear_usuario' %}">Crear nuevo usuario</a></td>
                </tr>
                <tr>
                    <td><a class="enlace" href="{%  url 'administrador:registrar_cen_edu' %}">Registrar un nuevo colegio</a></td>
                </tr>
                <tr>
                    <td><a class="enlace" href="/admin/administrador/colegio/">Consultar colegios</a></td>
                </tr>
                <tr class="botones">
                    <td colspan = "2">
                        <form name="crear_usuario" action="{% url 'login:end_session' %}" method="post">
                            {% csrf_token %}
                            <input class="boton" id="logout" type="submit" value="LogOut" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

administrador/templates/administrador/registrar_cen_edu.html
{% extends "administrador_base.html" %}

{% block title %} Registrar Centro Educativo {% endblock %}

{% block content %}
    <h1 class="titulo">
        {% if tipo_usuario != 'Nuevo_Usuario' %}
        {{ tipo_usuario }} <BR />
        {% endif %}
        Registrar Colegio
    </h1>

    <div class="tabla">
    <form name="crear_usuario" action="{% url 'administrador:crear_usuario' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                    <td class="etiqueta"><label for="nombre">Nombre:</label></td>
                    <td class="control"><input id="nombre" type="text" name="nombre" maxlength="100" autofocus="1"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="apellido">Apellido:</label></td>
                    <td class="control"><input id="apellido" type="text" name="apellido" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="email">E-Mail:</label></td>
                    <td class="control"><input id="email" type="text" name="email" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="radio" colspan = "2">
                        <label for="admin">Administrador</label>
                        <input id="admin" type="radio" name="tipo_usuario" value="admin">
                        &nbsp;&nbsp;
                        <label for="profesor">Profesor</label>
                        <input id="profesor" type="radio" name="tipo_usuario" value="profesor">                        &nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;
                        <label for="estudiante">Estudiante</label>
                        <input id="estudiante" type="radio" name="tipo_usuario" value="estudiante" checked>
                    </td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="username">Username:</label></td>
                    <td class="control"><input id="username" type="text" name="username" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="password">Password:</label></td>
                    <td class="control"><input id="password" type="password" name="password" maxlength="100"/></td>
                </tr>

                <tr class="botones">
                    <td colspan = "2">
                        <input id="origen" type="hidden" name="origen" value="Crear_Usuario">
                        <input class="boton" id="create" name="create" type="submit" value="Crear" />
                        <input class="boton" id="cancel" name="cancel" type="submit" value="Cancelar" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}

administrador/templates/administrador/registrar_colegio.html
{% extends "administrador_base.html" %}

{% block title %} Registrar Colegio {% endblock %}

{% block content %}
    <h1 class="titulo">
        {{ usuario }} <BR />
        Registrar Colegio
    </h1>

    <div class="tabla">
    <form name="crear_usuario" action="{% url 'administrador:crear_usuario' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                    <td class="etiqueta"><label for="nombre">Nombre:</label></td>
                    <td class="control"><input id="nombre" type="text" name="nombre" maxlength="100" autofocus="1"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="apellido">Apellido:</label></td>
                    <td class="control"><input id="apellido" type="text" name="apellido" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="email">E-Mail:</label></td>
                    <td class="control"><input id="email" type="text" name="email" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="radio" colspan = "2">
                        <label for="admin">Administrador</label>
                        <input id=admin" type="radio" name="tipo_usuario" value="admin">
                        &nbsp;&nbsp;
                        <label for="profesor">Profesor</label>
                        <input id="profesor" type="radio" name="tipo_usuario" value="profesor">                        &nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;
                        <label for="estudiante">Estudiante</label>
                        <input id="estudiante" type="radio" name="tipo_usuario" value="estudiante" checked>
                    </td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="username">Username:</label></td>
                    <td class="control"><input id="username" type="text" name="username" maxlength="100"/></td>
                </tr>
                <tr>
                    <td class="etiqueta"><label for="password">Password:</label></td>
                    <td class="control"><input id="password" type="password" name="password" maxlength="100"/></td>
                </tr>

                <tr class="botones">
                    <td colspan = "2">
                        <input id="origen" type="hidden" name="origen" value="Crear_Usuario">
                        <input class="boton" id="create" name="create" type="submit" value="Crear" />
                        <input class="boton" id="cancel" name="cancel" type="submit" value="Cancelar" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}

administrador/templates/administrador/seleccionar_cen_edu.html
{% extends "administrador_base.html" %}

{% block title %} Seleccionar Centro Educativo {% endblock %}

{% block content %}
    <h1 class="titulo">
        {% if tipo_usuario == "Administrador" %}
            {{ tipo_usuario }} <BR />
        {% endif %}
        Seleccionar Centro Educativo
    </h1>

    <div class="tabla" ng-controller="AdminController">
    <form name="crear_usuario" action="{% url 'administrador:seleccionar_cen_edu' %}" method="post">
        {% csrf_token %}
        <table class="formulario">
            <tbody>
                <tr>
                   {% verbatim %}
                    <td class="etiqueta"><label for="departamento">Departamento:</label></td>
                    <td class="control">
                        <select  id="departamento"
                                 ng-model="ang_departamento"
                                 ng-options="p.pk as p.departamento for p in ang_posts"
                                 ng-change="busca_cen_edu(ang_departamento, ang_tipo_cenedu)"
                                 name="departamento">
                            <option value="">-- Selecciona tu Departamento --</option>
                        </select>
                    </td>
                    {% endverbatim %}
                </tr>
                <tr>
                    <td class="radio" colspan = "2" >
                        <div ng-init="ang_tipo_cenedu='Colegio'">
                            <label for="colegio">Colegio</label>
                            <input id="colegio"
                                   type="radio"
                                   ng-model="ang_tipo_cenedu"
                                   ng-change="busca_cen_edu(ang_departamento, ang_tipo_cenedu)"
                                   name="cen_edu"
                                   value="Colegio">
                            &nbsp;&nbsp;
                            &nbsp;&nbsp;
                            <label for="universidad">Universidad</label>
                            <input id="universidad"
                                   type="radio"
                                   ng-model="ang_tipo_cenedu"
                                   ng-change="busca_cen_edu(ang_departamento, ang_tipo_cenedu)"
                                   name="cen_edu"
                                   value="Universidad">
                        </div>
                    </td>
                </tr>
                <tr ng-hide=" ang_departamento == null || ang_n_centros_edu == 0 ">
                    <td class="etiqueta"><label for="nombre">Nombre:</label></td>
                    <td class="control">
                        <select  id="cen_edu"
                                 ng-model="ang_nombre_cenedu"
                                 ng-options="ac.pk as ac.centro_educativo for ac in ang_centros_edu"
                                 ng-change="busca_cen_edu(ang_departamento, ang_tipo_cenedu)"
                                 name="departamento">
                            <option value="">-- Selecciona tu Centro Educativo --</option>
                        </select>
                    </td>
                </tr>
                <tr ng-hide=" ang_departamento == null ">
                    {% verbatim %}
                    <td colspan="2" class="mensaje">
                        <div ng-hide=" ang_n_centros_edu == 0 ">
                            ¿No aparece tu centro educativo?<BR/>
                            <a href="/administrador/registrar_cen_edu/{{ ang_departamento }}/{{ ang_cenedu }}">
                                Solicita su registro.
                            </a>
                        </div>
                        <div ng-show=" ang_n_centros_edu == 0 ">
                            No existen
                            <span ng-if="ang_tipo_cenedu=='Colegio'">colegios registrados</span>
                            <span ng-if="ang_tipo_cenedu=='Universidad'">universidades registradas</span><BR/>
                            <a href="/administrador/registrar_cen_edu/{{ ang_departamento }}/{{ ang_cenedu }}">
                                Solicita el registro de tu
                                <span ng-if="ang_tipo_cenedu=='Colegio'">colegio.</span>
                                <span ng-if="ang_tipo_cenedu=='Universidad'">universidad.</span><BR/>
                            </a>
                        </div>
                    </td>
                    {% endverbatim %}
                </tr>
                <tr ng-hide=" ang_departamento != null " >
                    <td colspan="2" class="mensaje">
                        Debes seleccionar un Departamento
                    </td>
                </tr>
                <tr class="botones">
                    <td colspan = "2">
                        <input id="origen" type="hidden" name="origen" value="Crear_Usuario">
                        <input class="boton" id="continuar" name="create" type="submit" value="Continuar" ng-hide=" ang_departamento == null " />
                        <input class="boton" id="cancel" name="cancel" type="submit" value="Cancelar" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    </div>

{% endblock %}